@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package codes.maxi.searchables.api.autcomplete;

import codes.maxi.searchables.MethodsReturnNonnullByDefault;
import codes.maxi.searchables.FieldsAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;